schema_version: 1

context:
  version: "2.8.0"
  python_min: "3.11"

package:
  name: dkx
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dkx/dkx-${{ version }}.tar.gz
  sha256: ee451d291bdeb66f3b34e9b0085100439a5fd551cf6a5fb6c3a2ad7089d5f20e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - dkx = dkx.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - jax
    - numpy >=2.1
    - scipy
    - h5py
    - netcdf4
    - matplotlib-base
    - rich >=13.0
    - solvax >=0.24.0

tests:
  - python:
      imports:
        - dkx
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - dkx --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Neoclassical transport solver with CPU/GPU and differentiable JAX workflows
  license: MIT
  license_file: LICENSE
  homepage: https://sfincs-jax.readthedocs.io/
  repository: https://github.com/uwplasma/DKX
  documentation: https://sfincs-jax.readthedocs.io/

extra:
  recipe-maintainers:
    - rogeriojorge
    - matthewfeickert
    - RKHashmani
